spring:
  datasource:
    url: jdbc:postgresql://localhost/product_catalog_admin
    username: postgres
    password: 123456

  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog.xml

  jpa:
    properties:
      hibernate: org.hibernate.dialect.PostgreSQL10Dialect
